### ISSUE TITLE
Handle missing github email 

### ISSUE THREAD

**Issue by kracekumar** [anandology/broadgauge#14]
Few github users don't expose the email address. As a result visiting the profile page of those trainers will raise `500 internal server error`. After successful authentication check for email. If missing prompt the user to enter the email.

**Comment by anandology** [comment]
added not null constraint to email. That'll make sure it won't happen again, but we need to show nice error message in those cases.

**Comment by anandology** [comment]
The whole point of using OAuth is to get verified people into the system. If github doesn't provide email, we should ask them to try with gmail.

**Comment by anandology** [comment]
I think 3f35d36155c8341226169950027632e92e18bfb6 takes care of that.
