### ISSUE TITLE
Mandrill integration and welcome email on signup

### ISSUE THREAD

**Issue by anandology** [anandology/broadgauge#16]
[Mandrill](http://www.mandrill.com/) is transactional email service from [MailChimp](http://www.mailchimp.com). They also provide API to handle incoming emails and I think we are going to need them. Integrate with Mandrill and send welcome email on signup.

**Comment by tarzzz** [comment]
I have some working code with mandrill integration. Can you please elaborate the functionality we want!

**Comment by tarzzz** [comment]
I have starting working here: #27 Please provide me some pointers on how to proceed!

**Comment by anandology** [comment]
I prefer to use envelops for sending emails. It should easy enough to switch to some other email provider if required.

Also, we should be able to send HTML emails. Please create `templates/emails/trainers/welcome.html` with some content and use it for sending email.

I think we should have sendmail module that can send emails using a template. I would expect an API like this:

```
from sendmail import sendmail
sendmail('trainers/welcome.html', trainer=trainer, to=trainer.email)
```

**Comment by tarzzz** [comment]
@anandology I have addressed your comments in #27. Please have a look

**Comment by anandology** [comment]
@tarzzz couple of issues with the implementation. 
1. rendering template is already solved in template.render_template. No need to do that all again.
2. subject should not be hard coded. It should either come from the template or passed as keyword argument. 
3. We shouldn't depend on mandrill python library. We would like something generic so that we can switch to something else if there is a need. I've already suggested using [envelopes](http://tomekwojcik.github.io/envelopes/).

**Comment by baijum** [comment]
@tarzzz Are you working on the suggestions given by @anandology ?

**Comment by anandology** [comment]
@baijum He sent a pull request, I need to merge it.

On Mon, Aug 11, 2014 at 10:37 PM, Baiju Muthukadan <notifications@github.com

> wrote:
> 
> @tarzzz https://github.com/tarzzz Are you working on the suggestions
> given by @anandology https://github.com/anandology ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/anandology/broadgauge/issues/16#issuecomment-51809324
> .

## 

Anand
http://anandology.com/

**Comment by tarzzz** [comment]
@baijum Yes, I have already addressed those suggestions in #27 . It needs to be reviewed and merged!

**Comment by baijum** [comment]
@tarzzz Nice !

@anandology I was looking for some urgent issues, Can you add all the issues/tasks we discussed ?

**Comment by anandology** [comment]
Done.

**Comment by anandology** [comment]
Thanks @tarzzz. I've merged your pull request and made some more improvements.
