### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by jaseemabid** [anandology/broadgauge#26]

**Comment by anandology** [comment]
No, I'm planning to add a real page soon.

**Comment by anandology** [comment]
Could you please change the title of this issue to "add about page"?

**Comment by jaseemabid** [comment]
Done. Do we have content?

**Comment by anandology** [comment]
No, I'll have to work on it.

On Wed, Jul 9, 2014 at 11:16 AM, Jaseem Abid notifications@github.com
wrote:

> Done. Do we have content?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/anandology/broadgauge/issues/26#issuecomment-48432316
> .

## 

Anand
http://anandology.com/
