### ISSUE TITLE
Admin should be able to assign trainer for the workshops

### ISSUE THREAD

**Issue by baijum** [anandology/broadgauge#32]
This is an essential feature required for release

**Comment by anandology** [comment]
@baijum could you please implement `/workshops/1/set-trainer` page to allow setting trainer for a workshop with access only to admins?

**Comment by baijum** [comment]
@anandology I can only look into this by around 8pm today

**Comment by baijum** [comment]
@anandology Should we display the link in the Workshop view page for admins ?
