### ISSUE TITLE
Show upcoming workshops on trainer profile page

### ISSUE THREAD

**Issue by anandology** [anandology/broadgauge#36]
@baijum can you work on this?

**Comment by baijum** [comment]
Sure, I can work on this today evening.

**Comment by baijum** [comment]
@anandology Please review pull request #38

**Comment by baijum** [comment]
@anandology The pull request #38 shows the upcoming workshop in Dashboard. Do we need to show it in the trainer's profile also ? `/trainers/(\d+)` ?

**Comment by anandology** [comment]
@baijum Yes, we need it on the trainer profile also.

**Comment by baijum** [comment]
@anandology I have updated the pull request to show the workshops in the trainer's profile page

**Comment by anandology** [comment]
Thanks @baijum. I've merged the pull request.
