### ISSUE TITLE
Admin should be able to delete workshop

### ISSUE THREAD

**Issue by baijum** [anandology/broadgauge#43]
Admin should be able to delete workshops. I think competed workshops need not be deleted.

**Comment by anandology** [comment]
I think we should only have an option to mark a workshop as hidden. We
shouldn't delete anything to avoid irrecoverable mistakes.

On Wed, Aug 13, 2014 at 3:32 PM, Baiju Muthukadan notifications@github.com
wrote:

> Admin should be able to delete workshops. I think competed workshops need
> not be deleted.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/anandology/broadgauge/issues/43.

## 

Anand
http://anandology.com/

**Comment by baijum** [comment]
@anandology agreed.

**Comment by iambibhas** [comment]
Add a `inactive` flag maybe.

**Comment by anandology** [comment]
There is a status flag and we can set the status flag to `inactive` to disable it. @baijum can you work on providing a way to do it form the interface?
