### ISSUE TITLE
Show a message to trainer when they express interest

### ISSUE THREAD

**Issue by baijum** [anandology/broadgauge#44]
We need to display a message to trainer when they express interest to conduct a workshop. 
`Thanks for your interest to conduct the workshop. The organization will contact you soon.`

**Comment by iambibhas** [comment]
Maybe add it here - 

![Thank you message](https://cloud.githubusercontent.com/assets/357253/3907766/d5268ec4-22fd-11e4-9071-f2e523ed723d.png)

**Comment by anandology** [comment]
Done.
