### ISSUE TITLE
trainers page list is broken

### ISSUE THREAD

**Issue by kracekumar** [anandology/broadgauge#5]
Url: http://demo.pythonexpress.in/trainers

![screen shot 2014-07-08 at 10 45 34 pm](https://cloud.githubusercontent.com/assets/311929/3513504/877b41de-06c3-11e4-8b53-f7fddf58f067.png)

**Comment by anandology** [comment]
Fixed.

**Comment by jaseemabid** [comment]
Broken again? 

![screen shot 2014-07-08 at 11 38 09 pm](https://cloud.githubusercontent.com/assets/601714/3514295/dd172d0e-06ca-11e4-99df-4b31d1f05ab6.png)

**Comment by anandology** [comment]
I think it is because of #14. I'll have a look at it.

**Comment by anandology** [comment]
Fixed now.

**Comment by jaseemabid** [comment]
That was fast :)
