### ISSUE TITLE
Show link to github profile from trainer page

### ISSUE THREAD

**Issue by anandology** [anandology/broadgauge#6]
When a trainer signs up using github account, his github profile is stored. Show the a link to github profile on trainer page.

**Comment by tarzzz** [comment]
Working on this one!

**Comment by anandology** [comment]
@tarzzz instructions to setup dev instance are available at https://github.com/anandology/broadgauge/blob/master/Readme.md#how-to-setup

**Comment by tarzzz** [comment]
Cool thanks. I made an issue regarding the install instructions. If that is done here, feel free to close the issue. #12

**Comment by anandology** [comment]
merged. Thanks @tarzzz.
