### ISSUE TITLE
Remove older events in dashboard.

### ISSUE THREAD

**Issue by kracekumar** [anandology/broadgauge#68]
Currently (August 23) events which were dated on August 20 are displayed. Remove old events from dashboard. Have a separate view for old events. I have logged in and url is http://www.pythonexpress.in/dashboard. 

```
Workshops that need trainers
Introduction to Python programming - 20 Aug 2014
ALiAS Open Source Conf. (AOSC) - 20 Aug 2014
```

are past events.

**Comment by kracekumar** [comment]
https://github.com/anandology/broadgauge/blob/a4eaf4c778355b6b8f4e02c83b2bedfad82bbe95/broadgauge/webapp.py#L52

```
  'get_pending_workshops': lambda: Workshop.findall(status='pending', order='date'),

```

need to have extra check `date > datetime.datetime.now().date()` something.

Does normal greater than sign work inside `findall` ?

**Comment by anandology** [comment]
I did that for homepage.

Ideally I would like to mark workshops as cancelled or completed.

On Sat, Aug 23, 2014 at 11:43 PM, Kracekumar Ramaraju <
notifications@github.com> wrote:

> https://github.com/anandology/broadgauge/blob/a4eaf4c778355b6b8f4e02c83b2bedfad82bbe95/broadgauge/webapp.py#L52
> 
>   'get_pending_workshops': lambda: Workshop.findall(status='pending', order='date'),
> 
> need to have extra check date > datetime.datetime.now().date() something.
> 
> Does normal greater than sign work inside findall.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/anandology/broadgauge/issues/68#issuecomment-53160859
> .

## 

Anand
http://anandology.com/
