### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by viggyprabhu** [anandology/broadgauge#70]
Currently there is no License for this project. It will be great if you can finalize the License and add the same in project. It will help other organizations to adopt/modify this project if they want to.

**Comment by arg0s** [comment]
+1 @anandology please update the License

**Comment by anandology** [comment]
License is only specified in the setup.py. I'll add it to Readme.

On Tue, Aug 26, 2014 at 4:40 PM, Aravind Krishnaswamy <
notifications@github.com> wrote:

> +1 @anandology https://github.com/anandology please update the License
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/anandology/broadgauge/issues/70#issuecomment-53404993
> .

## 

Anand
http://anandology.com/

**Comment by arg0s** [comment]
FYI - The GitHub convention is to drop a LICENSE file in at the top level.  For example: https://github.com/arg0s/flask-s3-direct-upload/blob/master/LICENSE

**Comment by anandology** [comment]
I knew it, but was lazy to add it. Will add it shortly.

On Tue, Aug 26, 2014 at 4:52 PM, Aravind Krishnaswamy <
notifications@github.com> wrote:

> FYI - The GitHub convention is to drop a LICENSE file in at the top level.
> For example:
> https://github.com/arg0s/flask-s3-direct-upload/blob/master/LICENSE
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/anandology/broadgauge/issues/70#issuecomment-53405914
> .

## 

Anand
http://anandology.com/
