### ISSUE TITLE
Show the contact person name and role on the org page

### ISSUE THREAD

**Issue by anandology** [anandology/broadgauge#8]
Each org has exactly one admin/coordinator. Show that info on org page.

It should read something like this:

Dummy College of Engineering and Technology
Bangalore

Contact Person:
Some One
HOD of Computer Science

**Comment by tarzzz** [comment]
Are we supposed to provide the admin's other details like his email id and/or phone number too?

**Comment by anandology** [comment]
Merged @tarzzz's pull request and did some other improvements.
